# Generated by Django 3.1.4 on 2021-01-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quack',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
