# Generated by Django 3.1.4 on 2021-01-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quacks', '0002_quack_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quack',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
