# Generated by Django 3.1.4 on 2021-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quacks', '0003_auto_20210103_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quack',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
