# Generated by Django 3.1.5 on 2021-01-05 20:39

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quacks', '0005_quack_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quack',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quack',
            name='likes',
        ),
        migrations.AddField(
            model_name='quack',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='quack_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
